[package]
name = "smartfan"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
chrono = "0.4"

[build]
target = ["x86_64-unknown-linux-musl", "x86_64-pc-windows-gnu", "x86_64-apple-darwin"]