[target.'cfg(target_os = "macos")'.x86_64-unknown-linux-musl]
linker = "rust-lld"

[target.'cfg(not(target_os = "macos"))'.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

[target.x86_64-apple-darwin]
linker = "rust-lld"